manual commands

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -141,12 +141,160 @@ jobs:
           #   echo << parameters.values-to-override >>
           #   echo $ROLE_ARN
           #   echo ${ROLE_ARN}
+      - run:
+        command: |
+          if [[ latest == "latest" ]]; then
+            # get latest kops release
+            KOPS_VERSION=$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)
+          else
+            KOPS_VERSION=latest
+          fi
+
+          PLATFORM="linux"
+          if [ -n "$(uname | grep "Darwin")" ]; then
+            PLATFORM="darwin"
+          fi
+
+          # download kops
+          curl -LO https://github.com/kubernetes/kops/releases/download/$KOPS_VERSION/kops-$PLATFORM-amd64
+
+          [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo
+
+          $SUDO chmod +x kops-$PLATFORM-amd64
+
+          $SUDO mv kops-$PLATFORM-amd64 /usr/local/bin/kops
+        name: Install kops
+    - run:
+        command: |
+          if [[ latest == "latest" ]]; then
+            # get latest kubectl release
+            KUBECTL_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
+          else
+            KUBECTL_VERSION=latest
+          fi
+
+          PLATFORM="linux"
+          if [ -n "$(uname | grep "Darwin")" ]; then
+            PLATFORM="darwin"
+          fi
+
+          # download kubectl
+          curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/$PLATFORM/amd64/kubectl
+
+          [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo
+
+          $SUDO chmod +x ./kubectl
+
+          $SUDO mv ./kubectl /usr/local/bin
+        name: Install kubectl
+    - run:
+        command: |
+          if which aws-iam-authenticator > /dev/null; then
+            echo "AWS IAM Authenticator for Kubernetes is already installed"
+            exit 0
+          fi
+
+          PLATFORM="linux"
+          if [ -n "$(uname | grep "Darwin")" ]; then
+            PLATFORM="darwin"
+          fi
+
+          RELEASE_TAG=""
+          RELEASE_URL="https://api.github.com/repos/kubernetes-sigs/aws-iam-authenticator/releases/latest"
+
+          FILENAME="aws-iam-authenticator"
+          VERSION=$(curl -Ls --fail --retry 3 -o /dev/null -w %{url_effective} "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/latest" | sed 's:.*/::')
+          if [ -n "${RELEASE_TAG}" ]; then
+            VERSION="${RELEASE_TAG}"
+            if [ "${VERSION}" == "v0.3.0" ]; then
+              FILENAME="heptio-authenticator-aws"
+            fi
+          fi
+
+          # extract version number
+          VERSION_NUMBER=$(echo $VERSION | cut -c 2-)
+
+          DOWNLOAD_URL="https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/${VERSION}/${FILENAME}_${VERSION_NUMBER}_${PLATFORM}_amd64"
+
+          curl -L --fail --retry 3 -o aws-iam-authenticator "$DOWNLOAD_URL"
+
+          chmod +x ./aws-iam-authenticator
+
+          SUDO=""
+          if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
+            SUDO="sudo"
+          fi
+
+          $SUDO mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
+        name: Install the AWS IAM Authenticator for Kubernetes
+    - run:
+        name: Install AWS CLI
+        command: |
+          export PIP=$(which pip pip3 | head -1)
+          if [[ -n $PIP ]]; then
+            if which sudo > /dev/null; then
+              sudo $PIP install awscli --upgrade
+            else
+              # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
+              $PIP install awscli --upgrade --user
+            fi
+          elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
+            cd
+            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
+            unzip awscli-bundle.zip
+            if which sudo > /dev/null; then
+              sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
+            else
+              # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
+              awscli-bundle/install -b ~/bin/aws
+            fi
+            rm -rf awscli-bundle*
+            cd -
+          else
+            echo "Unable to install AWS CLI. Please install pip."
+            exit 1
+          fi
+    - run:
+        command: |
+          CLUSTER_NAME="eks_auger-cluster-staging1"
+          AWS_REGION="us-west-2"
+          AWS_PROFILE=""
+          KUBECONFIG_FILE_PATH=""
+          CLUSTER_CONTEXT_ALIAS=""
+          DRY_RUN="false"
+          VERBOSE="false"
+          if [ -n "${CLUSTER_NAME}" ]; then
+            set -- "$@" --name "${CLUSTER_NAME}"
+          fi
+          if [ -n "${AWS_REGION}" ]; then
+            set -- "$@" --region "${AWS_REGION}"
+          fi
+          if [ -n "${AWS_PROFILE}" ]; then
+            set -- "$@" --profile "${AWS_PROFILE}"
+          fi
+          if [ -n "${KUBECONFIG_FILE_PATH}" ]; then
+            set -- "$@" --kubeconfig "${KUBECONFIG_FILE_PATH}"
+          fi
+          if [ -n "${ROLE_ARN}" ]; then
+            set -- "$@" --role-arn "${ROLE_ARN}"
+          fi
+          if [ -n "${CLUSTER_CONTEXT_ALIAS}" ]; then
+            set -- "$@" --alias "${CLUSTER_CONTEXT_ALIAS}"
+          fi
+          if [ "${DRY_RUN}" == "true" ]; then
+            set -- "$@" --dry-run
+          fi
+          if [ "${VERBOSE}" == "true" ]; then
+            set -- "$@" --verbose
+          fi
+          aws eks update-kubeconfig "$@"
+        name: Update the kubectl configuration file to use the authenticator
       # - kubernetes/install
-      - aws-eks/update-kubeconfig-with-authenticator:
-          cluster-name: << parameters.cluster-name >>
-          aws-region: << parameters.aws-region >>
-          cluster-authentication-role-arn: 'TEST'
-          install-kubectl: true
+      # - aws-eks/update-kubeconfig-with-authenticator:
+      #     cluster-name: << parameters.cluster-name >>
+      #     aws-region: << parameters.aws-region >>
+      #     cluster-authentication-role-arn: 'TEST'
+      #     install-kubectl: true
       # - helm/install-helm-chart:
       #     chart: augerai/a2ml
       #     release-name: a2ml
